# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ea50a8517282f7285fd14729877f94db1fe35c7e7d6fe59b9230dd4967f5775ec26de30dfde0743b6511a744334b7c77c4d00326054253ba433f2138b4405d0

test:
  secret_key_base: 3590222edbff1e20ebd3363b3f37ff288f877a9e45c7f6da9d591aa39289cf1b3cfe127070ed1edf2e97c376a4fea409d3287ac9e8588829858e2bf1015aa288

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
